

import React from 'react';
import { CloseIcon } from './icons/CloseIcon';

interface ModalProps {
    onClose: () => void;
    customContent?: string;
}

const H3: React.FC<{ children: React.ReactNode }> = ({ children }) => <h3 className="text-xl font-bold text-blue-400 mt-6 mb-2">{children}</h3>;
const P: React.FC<{ children: React.ReactNode }> = ({ children }) => <p className="leading-relaxed">{children}</p>;
const UL: React.FC<{ children: React.ReactNode }> = ({ children }) => <ul className="list-disc list-inside space-y-2 pl-4">{children}</ul>;
const LI: React.FC<{ children: React.ReactNode }> = ({ children }) => <li>{children}</li>;
const Strong: React.FC<{ children: React.ReactNode }> = ({ children }) => <strong className="font-semibold text-white">{children}</strong>;

const DefaultTerms = () => (
    <>
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        <P>By using this application ("Service"), you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, then you may not access the Service.</P>

        <H3>1. Use of Generated Content</H3>
        <P>The Service uses generative artificial intelligence to create images ("Creations") based on the inputs you provide. We do not claim any ownership rights to the Creations you generate using our Service.</P>
        <UL>
            <LI><Strong>Ownership and Copyright:</Strong> You are the owner of the Creations you generate. You are free to use, reproduce, modify, and distribute them for any purpose, including commercial use, as you see fit.</LI>
            <LI><Strong>No Manipulation by Us:</Strong> We do not review, edit, or manipulate the Creations generated by the AI. The output is provided to you as-is from the AI model.</LI>
        </UL>

        <H3>2. User Responsibility</H3>
        <P>You are solely responsible for the inputs you provide and the Creations you generate. You agree not to use the Service to create content that is:</P>
            <UL>
            <LI>Illegal, harmful, threatening, defamatory, obscene, or infringing on the rights of others.</LI>
            <LI>In violation of any intellectual property rights, including copyright and trademark, of any third party.</LI>
            <LI>In violation of any laws or regulations in your jurisdiction.</LI>
        </UL>
        <P>You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from your use of the Service or the Creations you generate.</P>
        
        <H3>3. Disclaimer of Warranties</H3>
        <P>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, regarding the operation or availability of the Service or the accuracy, reliability, or content of the Creations. The output of generative AI can be unpredictable, and we do not guarantee that the Creations will meet your specific requirements.</P>
        
        <H3>4. Limitation of Liability</H3>
        <P>In no event shall we be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</P>
        
            <H3>5. Changes to These Terms</H3>
        <P>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.</P>
    </>
);

export const TermsModal: React.FC<ModalProps> = ({ onClose, customContent }) => {
    return (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4" aria-modal="true" role="dialog">
            <div className="relative w-full max-w-4xl bg-gray-800 rounded-2xl shadow-2xl flex flex-col max-h-[90vh]">
                <div className="p-6 flex justify-between items-center border-b border-gray-700 flex-shrink-0">
                    <h2 className="text-2xl font-bold text-white">Terms & Conditions</h2>
                    <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors" aria-label="Close modal">
                        <CloseIcon className="w-7 h-7"/>
                    </button>
                </div>
                
                <div className="p-6 overflow-y-auto prose prose-invert prose-sm sm:prose-base max-w-none text-gray-300 space-y-4">
                    {customContent ? (
                        <pre className="whitespace-pre-wrap font-sans text-gray-300 text-base">{customContent}</pre>
                    ) : (
                        <DefaultTerms />
                    )}
                </div>

                <div className="p-4 flex justify-end gap-4 border-t border-gray-700 flex-shrink-0">
                    <button onClick={onClose} className="px-6 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700">
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};